### ISSUE TITLE
能否添加 验证码弹出框 手动输入验证码 这样触发验证码就不用手机在签到操作了

### ISSUE THREAD

**Issue by gdf159159** [Womsxd/MihoyoBBSTools#104]
能否添加 验证码弹出框 手动输入验证码 这样触发验证码就不用手机在签到操作了

**Comment by yriiolik** [comment]
可以参考下我的分支， 我用了个打码平台，不过是付费的。应该有一些免费的打码平台吧 可以找找

**Comment by angel12538** [comment]
> 可以参考下我的分支，我用了一个打码平台，不过是付费的。应该有一些免费的打码平台吧可以找找

您好，在使用您的分支之后运行程序出现了报错，报错代码如下，请问应该如何正确设置？
Traceback (most recent call last):
  File "C:\Users\1\Music\MihoyoBBSTools-master\main.py", line 147, in <module>
    status_code, message = main()
                           ^^^^^^
  File "C:\Users\1\Music\MihoyoBBSTools-master\main.py", line 113, in main
    return_data += checkin_game("genshin", genshin.Genshin, "原神")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Music\MihoyoBBSTools-master\main.py", line 27, in checkin_game
    return_data = f"\n\n{game_module().sign_account()}"
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Music\MihoyoBBSTools-master\gamecheckin.py", line 130, in sign_account
    req = self.check_in(account)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Music\MihoyoBBSTools-master\gamecheckin.py", line 96, in check_in
    validate = captcha.game_captcha(data["data"]["gt"], data["data"]["challenge"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Music\MihoyoBBSTools-master\captcha.py", line 12, in game_captcha
    response = geetest(gt, challenge, 'https://passport-api.mihoyo.com/account/ma-cn-passport/app/loginByPassword')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Music\MihoyoBBSTools-master\captcha.py", line 33, in geetest
    'appkey': config.config['captcha']['token'],
              ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'captcha'

**Comment by yriiolik** [comment]
要先去https://www.rrocr.com注册个账号，目前有没免费额度不清楚。 当然有能力可以换其他的打码平台。然后平台上会有个token，放到配置文件里的最下面：

```
....
cloud_games:
  genshin:
    enable: false
    token: ''
#最下面新增：
captcha:
  token: xxxxxxxxxxxxxx
```
