### ISSUE TITLE
显示识别2个配置文件，可只执行1个，而且没有提示成功或失败，实际是没成功。俩配置都true了···

### ISSUE THREAD

**Issue by 5963991** [Womsxd/MihoyoBBSTools#117]
2024-01-31T15:45:59 INFO AutoMihoyoBBS Multi User mode
2024-01-31T15:45:59 INFO 正在搜索配置文件！
2024-01-31T15:45:59 INFO 已搜索到2个配置文件，正在开始执行！
2024-01-31T15:45:59 INFO 正在执行mhy_[config2].yaml
Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 39, in <module>
    multi()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 24, in multi
    status_code, message = main_multi(True)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 55, in main_multi
    run_code, run_message = main.main()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 70, in main
    config.load_config()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/config.py", line 108, in load_config
    data = yaml.load(f, Loader=yaml.FullLoader)
  File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/ql/data/config/mhy_[config2].yaml", line 4, column 3
expected <block end>, but found '<scalar>'
  in "/ql/data/config/mhy_[config2].yaml", line 4, column 13

**Comment by 5963991** [comment]
💂‍♂️详细错误日志：

🛑脚本：Womsxd_MihoyoBBSTools_ql_main_255：
- ⚠Python错误：yaml.parser.ParserError: while parsing a block mapping 


🛑脚本：Womsxd_MihoyoBBSTools_ql_main_252：
- ⚠Python错误：yaml.parser.ParserError: while parsing a block mapping 






## 执行结束...   耗时 1 秒

**Comment by 5963991** [comment]
没搞懂映射失败是啥意思

**Comment by 5963991** [comment]
**应该是找到问题了，脚本格式问题，删除多余的就行了。**

2024-01-31T17:35:39 INFO AutoMihoyoBBS Multi User mode
2024-01-31T17:35:39 INFO 正在搜索配置文件！
2024-01-31T17:35:39 INFO 已搜索到3个配置文件，正在开始执行！
2024-01-31T17:35:39 INFO 正在执行mhy_[config2].yaml
2024-01-31T17:35:39 INFO Config加载完毕
2024-01-31T17:35:39 ERROR login_ticket(只有半小时有效期)已失效,请重新登录米游社抓取cookie
2024-01-31T17:35:39 INFO Cookie已删除
2024-01-31T17:35:39 INFO Config保存完毕
2024-01-31T17:35:39 INFO mhy_[config2].yaml执行完毕
2024-01-31T17:35:45 INFO 正在执行mhy_[config1].yaml
2024-01-31T17:35:45 INFO Config加载完毕
2024-01-31T17:35:45 ERROR login_ticket(只有半小时有效期)已失效,请重新登录米游社抓取cookie
2024-01-31T17:35:45 INFO Cookie已删除
2024-01-31T17:35:45 INFO Config保存完毕
2024-01-31T17:35:45 INFO mhy_[config1].yaml执行完毕
2024-01-31T17:35:48 INFO 正在执行mhy_[config3].yaml
2024-01-31T17:35:49 INFO Config加载完毕
2024-01-31T17:35:49 ERROR login_ticket(只有半小时有效期)已失效,请重新登录米游社抓取cookie
2024-01-31T17:35:49 INFO Cookie已删除
2024-01-31T17:35:49 INFO Config保存完毕
2024-01-31T17:35:49 INFO mhy_[config3].yaml执行完毕

2024-01-31T17:35:53 INFO 脚本执行完毕，共执行3个配置文件，成功0个，没执行0个，失败3个
没执行的配置文件: []
执行失败的配置文件: ['mhy_[config2].yaml', 'mhy_[config1].yaml', 'mhy_[config3].yaml']
触发游戏签到验证码的配置文件: [] 
2024-01-31T17:35:53 ERROR 全部配置文件错误！请检查配置文件！
米游社-全部配置错误

脚本执行完毕，共执行3个配置文件，成功0个，没执行0个，失败3个
没执行的配置文件: []
执行失败的配置文件: ['mhy_[config2].yaml', 'mhy_[config1].yaml', 'mhy_[config3].yaml']
触发游戏签到验证码的配置文件: []

**Comment by 5963991** [comment]
## 开始执行... 2024-01-31 17:54:46

2024-01-31T17:54:47 INFO AutoMihoyoBBS Multi User mode
2024-01-31T17:54:47 INFO 正在搜索配置文件！
2024-01-31T17:54:47 INFO 已搜索到2个配置文件，正在开始执行！
2024-01-31T17:54:47 INFO 正在执行mhy_[config2].yaml
2024-01-31T17:54:47 INFO Config加载完毕
2024-01-31T17:54:47 INFO 登录成功！
2024-01-31T17:54:47 INFO 正在保存Config！
2024-01-31T17:54:47 INFO Config保存完毕
2024-01-31T17:54:50 INFO 正在获取任务列表
2024-01-31T17:54:51 INFO 似乎还有任务没完成，今天还能获得10个米游币
2024-01-31T17:54:51 INFO 正在获取帖子列表......
2024-01-31T17:54:51 INFO 已获取5个帖子
2024-01-31T17:54:51 INFO 讨论区任务已经完成过了~
2024-01-31T17:54:51 INFO 看帖任务已经完成过了~
2024-01-31T17:54:51 INFO 点赞任务已经完成过了~
2024-01-31T17:54:51 INFO 正在执行分享任务......
2024-01-31T17:54:51 INFO 分享任务执行成功......
2024-01-31T17:54:58 INFO 正在获取任务列表
2024-01-31T17:54:58 INFO 今天已经获得110个米游币，还能获得0个米游币，目前有10430个米游币
2024-01-31T17:55:02 INFO 正在进行原神签到
2024-01-31T17:55:02 INFO 正在获取米哈游账号绑定的原神账号列表...
2024-01-31T17:55:03 INFO 已获取到1个原神账号信息
2024-01-31T17:55:03 INFO 正在获取签到奖励列表...
2024-01-31T17:55:03 INFO 正在为旅行者浅进行签到...
2024-01-31T17:55:11 INFO 旅行者浅今天已经签到过了~
今天获得的奖励是摩拉x5000
2024-01-31T17:55:11 INFO mhy_[config2].yaml执行完毕
2024-01-31T17:55:14 INFO 正在执行mhy_[config1].yaml
2024-01-31T17:55:14 INFO Config加载完毕
2024-01-31T17:55:14 INFO 登录成功！
2024-01-31T17:55:14 INFO 正在保存Config！
2024-01-31T17:55:14 INFO Config保存完毕
2024-01-31T17:55:17 INFO 正在获取任务列表
2024-01-31T17:55:17 INFO 似乎还有任务没完成，今天还能获得10个米游币
2024-01-31T17:55:17 INFO 正在获取帖子列表......
2024-01-31T17:55:18 INFO 已获取5个帖子
2024-01-31T17:55:18 INFO 讨论区任务已经完成过了~
2024-01-31T17:55:18 INFO 看帖任务已经完成过了~
2024-01-31T17:55:18 INFO 点赞任务已经完成过了~
2024-01-31T17:55:18 INFO 正在执行分享任务......
2024-01-31T17:55:18 INFO 分享任务执行成功......
2024-01-31T17:55:24 INFO 正在获取任务列表
2024-01-31T17:55:24 INFO 今天已经获得110个米游币，还能获得0个米游币，目前有23404个米游币
2024-01-31T17:55:34 INFO 正在进行原神签到
2024-01-31T17:55:34 INFO 正在获取米哈游账号绑定的原神账号列表...
2024-01-31T17:55:34 INFO 已获取到1个原神账号信息
2024-01-31T17:55:34 INFO 正在获取签到奖励列表...
2024-01-31T17:55:34 INFO 正在为旅行者深进行签到...
2024-01-31T17:55:38 INFO 旅行者深今天已经签到过了~
今天获得的奖励是摩拉x5000
2024-01-31T17:55:38 INFO 正在进行云原神签到
2024-01-31T17:55:39 WARNING 云原神token失效/防沉迷
2024-01-31T17:55:39 INFO 云原神Cookie删除完毕
2024-01-31T17:55:39 INFO Config保存完毕
2024-01-31T17:55:39 INFO mhy_[config1].yaml执行完毕

2024-01-31T17:55:49 INFO 脚本执行完毕，共执行2个配置文件，成功2个，没执行0个，失败0个
没执行的配置文件: []
执行失败的配置文件: []
触发游戏签到验证码的配置文件: [] 
米游社

脚本执行完毕，共执行2个配置文件，成功2个，没执行0个，失败0个
没执行的配置文件: []
执行失败的配置文件: []
触发游戏签到验证码的配置文件: [] 



## 执行结束...   耗时 63 秒　　　


### 已解决**已经确定是配置格式的问题了。**
