### ISSUE TITLE
提示获取签到奖励列表失败应该如何解决?

### ISSUE THREAD

**Issue by Mr-linao** [Womsxd/MihoyoBBSTools#121]
2024-02-17T01:05:55 WARNING 获取签到奖励列表失败
Traceback (most recent call last):
  File "/var/app/./main_multi.py", line 76, in <module>
    main_multi(autorun)
  File "/var/app/./main_multi.py", line 43, in main_multi
    run_code, run_message = main.main()
                            ^^^^^^^^^^^
  File "/var/app/main.py", line 93, in main
    genshin_help = genshin.Genshin()
                   ^^^^^^^^^^^^^^^^^
  File "/var/app/genshin.py", line 25, in __init__
    self.checkin_rewards = self.get_checkin_rewards()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/app/genshin.py", line 35, in get_checkin_rewards
    return data["data"]["awards"]
           ~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
{"data":null,"message":"活动已结束","retcode":-212}
2024-02-17T01:05:55 INFO Current running datetime: 2024-02-17 01:05:55
2024-02-17T01:05:55 INFO Next run datetime: 2024-02-17 09:30:01

**Comment by Womsxd** [comment]
请先更新脚本

**Comment by Mr-linao** [comment]
> 请先更新脚本

已解决,万分感谢
