### ISSUE TITLE
备份恢复后就这样了

### ISSUE THREAD

**Issue by iguri** [Womsxd/MihoyoBBSTools#128]
前几天备份data后重装了青龙，发现怎么都是这个错误，小白的我能解决吗
'''Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 8, in <module>
    from main import main
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 10, in <module>
    import competition
ModuleNotFoundError: No module named 'competition'''

**Comment by Womsxd** [comment]
重新配置拉取文件

**Comment by iguri** [comment]
> 重新配置拉取文件

从erpo文件里复制一份competition解决了，谢谢大佬
