### ISSUE TITLE
大佬咨询青龙面包报错

### ISSUE THREAD

**Issue by DR-lin-eng** [Womsxd/MihoyoBBSTools#137]
Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 41, in <module>
    single()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 14, in single
    status_code, message = main()
                           ^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 47, in main
    return_data += gamecheckin.run_task()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 233, in run_task
    return_data += checkin_game(game_name, game_module, game_print_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 213, in checkin_game
    if game_config["checkin"]:
       ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'checkin'

**Comment by Womsxd** [comment]
检查config.yaml

**Comment by DR-lin-eng** [comment]
> 检查config.yaml

谢谢支持
