### ISSUE TITLE
签到的时候报错：社区签到触发验证码 `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

### ISSUE THREAD

**Issue by scalpl** [Womsxd/MihoyoBBSTools#139]
```
2024-04-08T21:59:41 INFO 使用DOCKER运行米游社签到
2024-04-08T21:59:41 INFO Starting signing
2024-04-08T21:59:41 INFO AutoMihoyoBBS Multi User mode
2024-04-08T21:59:41 INFO 正在搜索配置文件！
2024-04-08T21:59:41 INFO 已搜索到6个配置文件，正在开始执行！
2024-04-08T21:59:41 INFO 正在执行mhy_Scal.yaml
2024-04-08T21:59:41 INFO Config加载完毕
2024-04-08T21:59:41 INFO 正在获取任务列表
2024-04-08T21:59:42 INFO 似乎还有任务没完成，今天还能获得40个米游币
2024-04-08T21:59:42 INFO 正在获取帖子列表......
2024-04-08T21:59:42 INFO 已获取5个帖子
2024-04-08T21:59:42 INFO 正在签到......

2024-04-08T21:59:41 INFO 使用DOCKER运行米游社签到
2024-04-08T21:59:41 INFO Starting signing
2024-04-08T21:59:41 INFO AutoMihoyoBBS Multi User mode
2024-04-08T21:59:41 INFO 正在搜索配置文件！
2024-04-08T21:59:41 INFO 已搜索到6个配置文件，正在开始执行！
2024-04-08T21:59:41 INFO 正在执行mhy_1113.yaml
2024-04-08T21:59:41 INFO Config加载完毕
2024-04-08T21:59:41 INFO 正在获取任务列表
2024-04-08T21:59:42 INFO 似乎还有任务没完成，今天还能获得40个米游币
2024-04-08T21:59:42 INFO 正在获取帖子列表......
2024-04-08T21:59:42 INFO 已获取5个帖子
2024-04-08T21:59:42 INFO 正在签到......2024-04-08T21:59:42 WARNING 社区签到触发验证码
Traceback (most recent call last):
  File "/var/app/./main_multi.py", line 91, in <module>
    main_multi(autorun)
  File "/var/app/./main_multi.py", line 57, in main_multi
    run_code, run_message = main.main()
                            ^^^^^^^^^^^
  File "/var/app/main.py", line 44, in main
    return_data += bbs.run_task()
                   ^^^^^^^^^^^^^^
  File "/var/app/mihoyobbs.py", line 239, in run_task
    self.signing()
  File "/var/app/mihoyobbs.py", line 145, in signing
    challenge = self.get_pass_challenge()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/app/mihoyobbs.py", line 62, in get_pass_challenge
    validate = captcha.bbs_captcha(data["data"]["gt"], data["data"]["challenge"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/app/captcha.py", line 33, in bbs_captcha
    ).json()  
      ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-04-08T21:59:46 INFO Current running datetime: 2024-04-08 21:59:46

```

captcha.py 文件内容：

```python
from request import http


def game_captcha(gt: str, challenge: str):
    # return None  # 失败返回None 成功返回validate
    rep = http.post(
        url= "http://api.rrocr.com/api/recognize.html",
        data={
            "appkey":"114514" ,
            "gt" : gt,
            "challenge" : challenge,
            "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign"
            }
    ).json()
    return rep["data"]["validate"] # 失败返回None 成功返回validate






def bbs_captcha(gt: str, challenge: str):
    # return None  # 失败返回None 成功返回validate
    rep = http.post(
        url= "http://api.rrocr.com/api/recognize.html",
        data={
            "appkey":"114514" ,
            "gt" : gt,
            "challenge" : challenge,
            "referer" : "https://api-takumi.mihoyo.com/event/bbs_sign_reward/sign"
        }
    ).json()
    return rep["data"]["validate"] # 失败返回None 成功返回validate

```

**Comment by mengluo04** [comment]
10041验证码？

**Comment by scalpl** [comment]
> 10041验证码？

什么意思

**Comment by mengluo04** [comment]
> > 10041验证码？
> 
> 什么意思

米游社风控验证码，最开始 是1034，可以直接过码。然后是10034，要加设备id再过码，前几天变成10041了，不知道又改了什么。当然，我说的是星穹铁道的接口。原神的也差不多，原神的还有5003
