### ISSUE TITLE
青龙执行报错

### ISSUE THREAD

**Issue by anpoz** [Womsxd/MihoyoBBSTools#14]
## 开始执行... 2023-03-16 17:40:10

通知发送成功
2023-03-16T17:40:19 INFO AutoMihoyoBBS Multi User mode
2023-03-16T17:40:19 INFO 正在搜索配置文件！
2023-03-16T17:40:19 INFO 已搜索到2个配置文件，正在开始执行！
2023-03-16T17:40:19 INFO 正在执行mhy_223904303.yaml
2023-03-16T17:40:19 INFO Config加载完毕
2023-03-16T17:40:19 INFO 正在获取任务列表
2023-03-16T17:40:20 INFO 今天已经全部完成了！一共获得90个米游币，目前有4680个米游币
2023-03-16T17:40:20 INFO 正在进行原神签到
2023-03-16T17:40:20 INFO 正在获取米哈游账号绑定的原神账号列表...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 62, in start_tls
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 57, in start_tls
    sock = ssl_context.wrap_socket(
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:980: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 54, in start_tls
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout: _ssl.c:980: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 39, in <module>
    multi()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 24, in multi
    status_code, message = main_multi(True)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 52, in main_multi
    run_code, run_message = main.main()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 93, in main
    genshin_help = genshin.Genshin()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/genshin.py", line 23, in __init__
    self.account_list = get_account_list("hk4e_cn", self.headers)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/account.py", line 11, in get_account_list
    req = http.get(setting.account_Info_url + game_id, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1045, in get
    return self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 908, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:980: The handshake operation timed out

## 执行结束... 2023-03-16 17:40:41  耗时 31 秒

**Comment by ShanshanHY** [comment]
> ## 开始执行... 2023-03-16 17:40:10
> 通知发送成功 2023-03-16T17:40:19 INFO AutoMihoyoBBS Multi User mode 2023-03-16T17:40:19 INFO 正在搜索配置文件！ 2023-03-16T17:40:19 INFO 已搜索到2个配置文件，正在开始执行！ 2023-03-16T17:40:19 INFO 正在执行mhy_223904303.yaml 2023-03-16T17:40:19 INFO Config加载完毕 2023-03-16T17:40:19 INFO 正在获取任务列表 2023-03-16T17:40:20 INFO 今天已经全部完成了！一共获得90个米游币，目前有4680个米游币 2023-03-16T17:40:20 INFO 正在进行原神签到 2023-03-16T17:40:20 INFO 正在获取米哈游账号绑定的原神账号列表... Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions yield File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 62, in start_tls raise exc File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 57, in start_tls sock = ssl_context.wrap_socket( File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket return self.sslsocket_class._create( File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create self.do_handshake() File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake self._sslobj.do_handshake() TimeoutError: _ssl.c:980: The handshake operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions yield File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request resp = self._pool.handle_request(req) File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request raise exc File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request response = connection.handle_request(request) File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 86, in handle_request raise exc File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 63, in handle_request stream = self._connect(request) File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 150, in _connect stream = stream.start_tls(**kwargs) File "/usr/local/lib/python3.10/site-packages/httpcore/backends/sync.py", line 54, in start_tls with map_exceptions(exc_map): File "/usr/local/lib/python3.10/contextlib.py", line 153, in **exit** self.gen.throw(typ, value, traceback) File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions raise to_exc(exc) httpcore.ConnectTimeout: _ssl.c:980: The handshake operation timed out
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 39, in multi() File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 24, in multi status_code, message = main_multi(True) File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 52, in main_multi run_code, run_message = main.main() File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 93, in main genshin_help = genshin.Genshin() File "/ql/data/scripts/Womsxd_MihoyoBBSTools/genshin.py", line 23, in **init** self.account_list = get_account_list("hk4e_cn", self.headers) File "/ql/data/scripts/Womsxd_MihoyoBBSTools/account.py", line 11, in get_account_list req = http.get(setting.account_Info_url + game_id, headers=headers) File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1045, in get return self.request( File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 821, in request return self.send(request, auth=auth, follow_redirects=follow_redirects) File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 908, in send response = self._send_handling_auth( File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 936, in _send_handling_auth response = self._send_handling_redirects( File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 973, in _send_handling_redirects response = self._send_single_request(request) File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1009, in _send_single_request response = transport.handle_request(request) File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request with map_httpcore_exceptions(): File "/usr/local/lib/python3.10/contextlib.py", line 153, in **exit** self.gen.throw(typ, value, traceback) File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions raise mapped_exc(message) from exc httpx.ConnectTimeout: _ssl.c:980: The handshake operation timed out
> 
> ## 执行结束... 2023-03-16 17:40:41 耗时 31 秒

最后的报错是`The handshake operation timed out`，应该是网络问题
检查下网络链接或者有没有使用代理？

**Comment by anpoz** [comment]
我是挂在vps上使用的，应该没有代理方面问题。当时也就是当天有问题，后面就再也没有问题了，可能是网络问题吧。
