### ISSUE TITLE
青龙面板运行报错

### ISSUE THREAD

**Issue by Cxyofficial** [Womsxd/MihoyoBBSTools#149]
## 开始执行... 2024-05-11 21:15:13

Traceback (most recent call last):
  File "/ql/data/scripts/yriiolik_MihoyoBBSTools/ql_main.py", line 8, in <module>
    from main import main
  File "/ql/data/scripts/yriiolik_MihoyoBBSTools/main.py", line 5, in <module>
    import push
  File "/ql/data/scripts/yriiolik_MihoyoBBSTools/push.py", line 5, in <module>
    import config
  File "/ql/data/scripts/yriiolik_MihoyoBBSTools/config.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

## 执行结束... 2024-05-11 21:15:15  耗时 2 秒

**Comment by chris31326** [comment]
你的config.yaml还没配啊，看看readme先

**Comment by Womsxd** [comment]
缺少依赖
