### ISSUE TITLE
请问一下. 这个错误信息是指?

### ISSUE THREAD

**Issue by AIsht669** [Womsxd/MihoyoBBSTools#153]
2024-05-21T16:58:05 INFO Config加载完毕
2024-05-21T16:58:09 INFO 正在进行原神签到
2024-05-21T16:58:09 INFO 正在获取米哈游账号绑定的原神账号列表...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 93, in handle_request
    self._send_request_headers(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 151, in _send_request_headers
    with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.LocalProtocolError: Illegal header value b'cookie_token_v2=v2_4EQ0YnPpTHdJmErkicHFulDv2bce90gKPFLJXy4-jmYr4OeDxP9kP9xR2hRIZizlaKFbi2gSA=.CAE=; account_mid_v2=0vfucl_mhy; account_id_v2=20791; ltoken_v2=v2_0iaRpDaYyS5Sl_rYZQ=.CAE=; ltmid_v2=0zfucl_mhy; ltuid_v2=20391; '

请问一下.

**Comment by Cxy-2008** [comment]
关闭bbs功能即可

**Comment by FangV5** [comment]
> 关闭bbs功能即可

关了我也报一样的错

**Comment by Womsxd** [comment]
这是你的cookie情况：;空格' 
请改成: '
把;和空格给删掉
