### ISSUE TITLE
麻烦问下，青龙平台报错

### ISSUE THREAD

**Issue by w211691** [Womsxd/MihoyoBBSTools#158]
## 开始执行... 2024-06-12 09:00:11

2024-06-12T09:00:11 INFO AutoMihoyoBBS Multi User mode
2024-06-12T09:00:11 INFO 正在搜索配置文件！
2024-06-12T09:00:11 INFO 已搜索到1个配置文件，正在开始执行！
2024-06-12T09:00:11 INFO 正在执行mhy_[config1].yaml
2024-06-12T09:00:11 INFO Config加载完毕
2024-06-12T09:00:11 INFO 正在获取任务列表
2024-06-12T09:00:12 INFO 新的一天，今天可以获得110个米游币
2024-06-12T09:00:12 INFO 正在获取帖子列表......
2024-06-12T09:00:12 INFO 已获取5个帖子
2024-06-12T09:00:12 INFO 正在签到......
2024-06-12T09:00:12 WARNING 社区签到触发验证码
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 39, in <module>
    multi()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 24, in multi
    status_code, message = main_multi(True)
                           ^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 62, in main_multi
    run_code, run_message = main.main()
                            ^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 45, in main
    return_data += bbs.run_task()
                   ^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 240, in run_task
    self.signing()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 146, in signing
    challenge = self.get_pass_challenge()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 63, in get_pass_challenge
    validate = captcha.bbs_captcha(data["data"]["gt"], data["data"]["challenge"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/captcha.py", line 44, in bbs_captcha
    rep = http.post(
          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1145, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

## 执行结束... 2024-06-12 09:00:33  耗时 22 秒　　　　　

这个是打码平台挂了导致的吗？

**Comment by Womsxd** [comment]
time out 打码平台超时，推荐修改超时时长
.get('http://example.com/api/v1/example', timeout=120)
修改超时时长为2分钟

**Comment by w211691** [comment]
> time out 打码平台超时，推荐修改超时时长 .get（'http://example.com/api/v1/example'， timeout=120） 修改超时时长为2分钟

感谢，是在captcha.py里这样修改吗？
def game_captcha(gt: str, challenge: str):
    rep = http.post(
       url= ".get（'http://example.com/api/v1/example'， timeout=120）",
       data={
           "appkey": "XXXXXXXXX",
           "gt": gt,
           "challenge" : challenge,
           "referer" : "https://api-takumi.mihoyo.com/event/luna/sign"
           }
    ).json()
    return rep["data"]["validate"]
