### ISSUE TITLE
为什么会这样

### ISSUE THREAD

**Issue by haoge369** [Womsxd/MihoyoBBSTools#164]
PS C:\Users\Administrator\Desktop\MihoyoBBSTools-master> python main_multi.py autorun
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MihoyoBBSTools-master\main_multi.py", line 3, in <module>
    import main
  File "C:\Users\Administrator\Desktop\MihoyoBBSTools-master\main.py", line 5, in <module>
    import push
  File "C:\Users\Administrator\Desktop\MihoyoBBSTools-master\push.py", line 5, in <module>
    import config
  File "C:\Users\Administrator\Desktop\MihoyoBBSTools-master\config.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by Womsxd** [comment]
[readme](https://github.com/Womsxd/MihoyoBBSTools?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E7%A8%8B%E5%BA%8F)
