### ISSUE TITLE
大佬,请问这个报错是什么问题

### ISSUE THREAD

**Issue by a342617810** [Womsxd/MihoyoBBSTools#166]
昨天第一次配置完config后,签到正常,今天第二次签到就报错了,关了游戏签到部分不会报错,米币正常

## 开始执行... 2024-06-30 01:12:00

2024-06-30T01:12:01 INFO Config加载完毕
2024-06-30T01:12:01 INFO 正在获取任务列表
2024-06-30T01:12:02 INFO 新的一天，今天可以获得90个米游币
2024-06-30T01:12:02 INFO 正在获取帖子列表......
2024-06-30T01:12:02 INFO 已获取5个帖子
2024-06-30T01:12:02 INFO 正在签到......
2024-06-30T01:12:02 INFO 大别野OK
2024-06-30T01:12:09 INFO 原神OK
2024-06-30T01:12:11 INFO 正在看帖......
2024-06-30T01:12:31 INFO 正在点赞......
2024-06-30T01:13:19 INFO 正在执行分享任务......
2024-06-30T01:13:19 INFO 分享任务执行成功......
2024-06-30T01:13:24 INFO 正在获取任务列表
2024-06-30T01:13:25 INFO 今天已经获得90个米游币，还能获得0个米游币，目前有3419个米游币
2024-06-30T01:13:38 INFO 正在进行崩坏3rd签到
2024-06-30T01:13:38 INFO 正在获取米哈游账号绑定的崩坏3账号列表...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 93, in handle_request
    self._send_request_headers(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 151, in _send_request_headers
    with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.LocalProtocolError: Illegal header value b'按步骤获取的cookie内容'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 41, in <module>
    single()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 14, in single
    status_code, message = main()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 48, in main
    return_data += gamecheckin.run_task()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 233, in run_task
    return_data += checkin_game(game_name, game_module, game_print_name)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 218, in checkin_game
    return_data = f"\n\n{game_module().sign_account()}"
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 180, in __init__
    super().__init__("bh3_cn", "honkai3rd", "崩坏3", setting.honkai3rd_act_id, "舰长")
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 36, in __init__
    self.account_list = self.get_account_list()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 57, in get_account_list
    account_list = get_account_list(self.game_id, self.headers)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/account.py", line 19, in get_account_list
    response = http.get(setting.account_Info_url, params={"game_biz": game_id}, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Illegal header value b'按步骤获取的cookie内容'

**Comment by a342617810** [comment]
补充:青龙2.15.4

**Comment by LANCHONGe** [comment]
我也出现了这个问题

**Comment by Womsxd** [comment]
b'按步骤获取的cookie内容' 是直接出现了这个文本还是什么情况？

**Comment by clionertr** [comment]
我的情况相同。我只填写了config.yaml的stuid,stoken,和mid。cookie留空，因为我使用步骤提供的cookie提示cookie有误

**Comment by clionertr** [comment]
实测account项目下的填好，device下的id填好就行。cookie按要求的填
![Uploading 屏幕截图 2024-07-08 192521.png…]()

**Comment by a342617810** [comment]
> b'按步骤获取的cookie内容' 是直接出现了这个文本还是什么情况？

是我自己的cookie,正常的

**Comment by Womsxd** [comment]
> > b'按步骤获取的cookie内容' 是直接出现了这个文本还是什么情况？
> 
> 是我自己的cookie,正常的

现在怀疑是不是你cookie最后有个空格了
