### ISSUE TITLE
使用青龙版面推送的时候报错，但是正常推送

### ISSUE THREAD

**Issue by runishiwo** [Womsxd/MihoyoBBSTools#167]
自定义通知服务启动
Exception in thread custom_notify:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/notify.py", line 814, in custom_notify
    formatUrl, formatBody = format_notify_content(
ValueError: not enough values to unpack (expected 2, got 0)
企业微信机器人推送成功！
企业微信推送成功！

额这个报错有影响吗，签到什么的都正常，推送也正常，除了有这个报错

**Comment by Womsxd** [comment]
不影响
