### ISSUE TITLE
麻烦问下，绝区零签到是换验证方式了？

### ISSUE THREAD

**Issue by w211691** [Womsxd/MihoyoBBSTools#179]
## 开始执行... 2024-07-18 11:03:11

2024-07-18T11:03:12 INFO AutoMihoyoBBS Multi User mode
2024-07-18T11:03:12 INFO 正在搜索配置文件！
2024-07-18T11:03:12 INFO 已搜索到1个配置文件，正在开始执行！
2024-07-18T11:03:12 INFO 正在执行mhy_[config1].yaml
2024-07-18T11:03:12 INFO Config加载完毕
2024-07-18T11:03:12 INFO 正在获取任务列表
2024-07-18T11:03:12 INFO 今天已经全部完成了！一共获得110个米游币，目前有29700个米游币
2024-07-18T11:03:19 INFO 正在进行原神签到
2024-07-18T11:03:19 INFO 正在获取米哈游账号绑定的原神账号列表...
2024-07-18T11:03:19 INFO 已获取到1个原神账号信息
2024-07-18T11:03:19 INFO 正在获取签到奖励列表...
2024-07-18T11:03:20 INFO 正在为旅行者泰拉的天诺战士进行签到...
2024-07-18T11:03:24 INFO 旅行者泰拉的天诺战士今天已经签到过了~
今天获得的奖励是原石x20
2024-07-18T11:03:28 INFO 正在进行绝区零签到
2024-07-18T11:03:28 INFO 正在获取米哈游账号绑定的绝区零账号列表...
2024-07-18T11:03:28 INFO 已获取到1个绝区零账号信息
2024-07-18T11:03:28 INFO 正在获取签到奖励列表...
2024-07-18T11:03:28 INFO 正在为绳匠泰拉的天诺战士进行签到...
Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 39, in <module>
    multi()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 24, in multi
    status_code, message = main_multi(True)
                           ^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 62, in main_multi
    run_code, run_message = main.main()
                            ^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 48, in main
    return_data += gamecheckin.run_task()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 245, in run_task
    return_data += checkin_game(game_name, game_module, game_print_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 229, in checkin_game
    return_data = f"\n\n{game_module().sign_account()}"
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 142, in sign_account
    req = self.check_in(account)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/gamecheckin.py", line 108, in check_in
    validate = captcha.game_captcha(data["data"]["gt"], data["data"]["challenge"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/captcha.py", line 36, in game_captcha
    response = geetest(gt, challenge, 'https://passport-api.mihoyo.com/account/ma-cn-passport/app/loginByPassword')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/captcha.py", line 57, in geetest
    'appkey': config.config['captcha']['token'],
              ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'captcha'

## 执行结束... 2024-07-18 11:03:41  耗时 30 秒　　　　　

原神的验证过了，但是绝区零的过不了，不知道是不是换验证方式了

**Comment by w211691** [comment]
## 开始执行... 2024-07-19 09:06:52

2024-07-19T09:06:53 INFO AutoMihoyoBBS Multi User mode
2024-07-19T09:06:53 INFO 正在搜索配置文件！
2024-07-19T09:06:53 INFO 已搜索到1个配置文件，正在开始执行！
2024-07-19T09:06:53 INFO 正在执行mhy_[config1].yaml
2024-07-19T09:06:53 INFO Config加载完毕
2024-07-19T09:06:53 INFO 正在获取任务列表
2024-07-19T09:06:53 INFO 新的一天，今天可以获得110个米游币
2024-07-19T09:06:53 INFO 正在获取帖子列表......
2024-07-19T09:06:53 INFO 已获取5个帖子
2024-07-19T09:06:53 INFO 正在签到......
2024-07-19T09:06:54 WARNING 社区签到触发验证码
Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 39, in <module>
    multi()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 24, in multi
    status_code, message = main_multi(True)
                           ^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 62, in main_multi
    run_code, run_message = main.main()
                            ^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 45, in main
    return_data += bbs.run_task()
                   ^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 240, in run_task
    self.signing()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 146, in signing
    challenge = self.get_pass_challenge()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 63, in get_pass_challenge
    validate = captcha.bbs_captcha(data["data"]["gt"], data["data"]["challenge"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/captcha.py", line 45, in bbs_captcha
    response = geetest(gt, challenge,
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/captcha.py", line 57, in geetest
    'appkey': config.config['captcha']['token'],
              ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'captcha'

## 执行结束... 2024-07-19 09:06:54  耗时 2 秒　

今天社区开始报错了

**Comment by Womsxd** [comment]
captcha.py的问题

**Comment by w211691** [comment]
> captcha.py的问题

的确是我的问题，排查完毕，谢谢
