### ISSUE TITLE
Docker运行和直接python main.py运行都报错

### ISSUE THREAD

**Issue by Mo-Qiong** [Womsxd/MihoyoBBSTools#19]
Docker运行：
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (charset-normalizer 3.0.1 (/usr/local/lib/python3.6/site-packages), Requirement.parse('charset-normalizer~=2.0.0; python_version >= "3"'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'charset-normalizer~=2.0.0; python_version >= "3"' distribution was not found and is required by requests

Python直接本地运行：
2023-03-27T02:27:02 INFO Config加载完毕
2023-03-27T02:27:02 WARNING Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
2023-03-27T02:27:02 WARNING Retrying (Retry(total=8, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
2023-03-27T02:27:02 WARNING Retrying (Retry(total=7, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
2023-03-27T02:27:02 WARNING Retrying (Retry(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
2023-03-27T02:27:02 WARNING Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
2023-03-27T02:27:02 WARNING Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
2023-03-27T02:27:02 WARNING Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
2023-03-27T02:27:02 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
2023-03-27T02:27:02 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
2023-03-27T02:27:02 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 692, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 281, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1011, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='webapi.account.mihoyo.com', port=443): Max retries exceeded with url: /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/MihoyoBBSTools/main.py", line 117, in <module>
    status_code, message = main()
  File "/root/MihoyoBBSTools/main.py", line 28, in main
    login.login()
  File "/root/MihoyoBBSTools/login.py", line 21, in login
    data = http.get(url=setting.bbs_cookie_url.format(config.config["account"]["login_ticket"])).json()
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='webapi.account.mihoyo.com', port=443): Max retries exceeded with url: /Api/cookie_accountinfo_by_loginticket?login_ticket=tN1tlwSQBWU9rprsXyPh1XED0CVSESvYxhd5LQLN (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Comment by TonyWang2233** [comment]
缺少所需第三方模块，执行 pip install -r requirements.txt 安装模块
