### ISSUE TITLE
[BUG] 国际服签到（绝区零）失败

### ISSUE THREAD

**Issue by Orokapei** [Womsxd/MihoyoBBSTools#197]
Qinglong 2.17.11 绝区零签到失败，最后一次成功签到时间为 2024-10-10，失败日志如下：
```
Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 49, in <module>
    multi()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 34, in multi
    status_code, message = main_multi(True)
                           ^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 63, in main_multi
    run_code, run_message = main.main()
                            ^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 67, in main
    os_result = hoyo_checkin.run_task()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/hoyo_checkin.py", line 136, in run_task
    ret_msg += f"\n\n{globals()[game]()}"
                      ^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/hoyo_checkin.py", line 118, in zzz
    ret_msg = '绝区零:\n' + hoyo_checkin("https://sg-act-nap-api.hoyolab.com/event/luna/zzz/os",
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/hoyo_checkin.py", line 38, in hoyo_checkin
    today = info_list.get("data", {}).get("today")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
自己看了一下，是不是跟headers有关，GET `https://sg-act-nap-api.hoyolab.com/event/luna/zzz/os/info?lang=zh-cn&act_id=e202406031448091`的时候如果只带ck会返回：
```
{
    "data": null,
    "message": "网络出小差了，请稍后重试~",
    "retcode": -500001
}
```
headers带上`x-rpc-signgame: zzz`才能正确返回数据：
```
{
    "retcode": 0,
    "message": "OK",
    "data": {
        "total_sign_day": 12,
        "today": "2024-10-14",
        "is_sign": true,
        "is_sub": false,
        "region": "",
        "sign_cnt_missed": 2,
        "short_sign_day": 0,
        "send_first": false
    }
}
```
在仓库搜了一下好像只有国服设置了headers
https://github.com/Womsxd/MihoyoBBSTools/blob/3010241e0e2913a8cea3d7b4e27ea01b8aa3e1db/gamecheckin.py#L213-L221
或者还有其他的原因导致签到失败？= =

**Comment by Womsxd** [comment]
估计后面都要加了

**Comment by Orokapei** [comment]
已成功签到，感谢🫶
