### ISSUE TITLE
云原神签到失败了

### ISSUE THREAD

**Issue by piaoying9** [Womsxd/MihoyoBBSTools#199]
日志：
`2024-10-22T23:10:10 INFO 正在进行云原神签到
Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 49, in <module>
    multi()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 34, in multi
    status_code, message = main_multi(True)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 63, in main_multi
    run_code, run_message = main.main()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 73, in main
    return_data += "\n\n" + cloud_genshin.run_task()
AttributeError: module 'cloud_genshin' has no attribute 'run_task'`
不知道啥原因，之前一直正常的

**Comment by Womsxd** [comment]
青龙吗？更新下拉取命令

**Comment by piaoying9** [comment]
> 青龙吗？更新下拉取命令

对的，青龙，抱歉没有发现订阅规则有变化，依赖增加了，现在没问题了
