### ISSUE TITLE
青龙运行报错No module named 'cloudgames'

### ISSUE THREAD

**Issue by hcv2** [Womsxd/MihoyoBBSTools#205]
## 开始执行... 2024-11-22 09:35:49

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 9, in <module>
    from main import main
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 13, in <module>
    import cloudgames
ModuleNotFoundError: No module named 'cloudgames'

**Comment by Womsxd** [comment]
更新订阅配置
