### ISSUE TITLE
更新后青龙运行报错（push相关）

### ISSUE THREAD

**Issue by QYC-Unity** [Womsxd/MihoyoBBSTools#206]
没有配置推送相关的环境变量
日志如下
2024-11-25T11:08:41 WARNING 配置文件 /ql/data/scripts/Womsxd_MihoyoBBSTools/config/push.ini 不存在！
Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 49, in <module>
    multi()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 34, in multi
    status_code, message = main_multi(True)
                           ^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 88, in main_multi
    push.push(status, push_message)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/push.py", line 433, in push
    return push_handler_instance.push(status, push_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/push.py", line 403, in push
    if not self.cfg.getboolean('setting', 'enable'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 844, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 824, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 819, in _get
    return conv(self.get(section, option, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 1170, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'setting'

**Comment by Womsxd** [comment]
已完成修复
