### ISSUE TITLE
推送报错，完整运行日志如下

### ISSUE THREAD

**Issue by hggg666** [Womsxd/MihoyoBBSTools#210]
[2024-11-29 14:24:48:042] 执行开始
2024-11-29T14:24:48 INFO Config加载完毕
2024-11-29T14:24:48 INFO 正在获取任务列表
2024-11-29T14:24:48 INFO 今天已经全部完成了！一共获得90个米游币，目前有31500个米游币
2024-11-29T14:24:50 INFO 正在进行崩坏: 星穹铁道签到
2024-11-29T14:24:51 INFO 正在获取米哈游账号绑定的崩坏： 星穹铁道账号列表...
2024-11-29T14:24:51 INFO 已获取到1个崩坏： 星穹铁道账号信息
2024-11-29T14:24:51 INFO 正在获取签到奖励列表...
2024-11-29T14:24:51 INFO 正在为开拓者xx进行签到...
Traceback (most recent call last):
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_backends/sync.py", line 28, in read
    return self._sock.recv(max_bytes)
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_sync/connection_pool.py", line 262, in handle_request
    raise exc
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_sync/connection.py", line 96, in handle_request
    return self._connection.handle_request(request)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_sync/http11.py", line 121, in handle_request
    raise exc
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_sync/http11.py", line 99, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_sync/http11.py", line 164, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_sync/http11.py", line 200, in _receive_event
    data = self._network_stream.read(
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_backends/sync.py", line 26, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/arcadia/repo/hggg666_MihoyoBBSTools/main.py", line 94, in <module>
    status_code, message = main()
  File "/arcadia/repo/hggg666_MihoyoBBSTools/main.py", line 64, in main
    return_data += gamecheckin.run_task()
  File "/arcadia/repo/hggg666_MihoyoBBSTools/gamecheckin.py", line 247, in run_task
    return_data += checkin_game(game_name, game_module, game_print_name)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/gamecheckin.py", line 231, in checkin_game
    return_data = f"\n\n{game_module().sign_account()}"
  File "/arcadia/repo/hggg666_MihoyoBBSTools/gamecheckin.py", line 144, in sign_account
    req = self.check_in(account)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/gamecheckin.py", line 110, in check_in
    validate = captcha.game_captcha(data["data"]["gt"], data["data"]["challenge"])
  File "/arcadia/repo/hggg666_MihoyoBBSTools/captcha.py", line 8, in game_captcha
    rep = http.post(
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_client.py", line 1132, in post
    return self.request(
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/arcadia/repo/hggg666_MihoyoBBSTools/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out
[2024-11-29 14:25:36:323] 执行完毕，总用时 48 秒

**Comment by Womsxd** [comment]
网络请求超时了，要不改改request.py里面的httpx的timeout时间？

**Comment by hggg666** [comment]
request.py里面的httpx的timeout改成60秒后，验证码那里再加多一个30秒的超时才跑过，这应该是打码平台超时太久了，大佬有啥好用便宜的打码平台推荐吗？
![image](https://github.com/user-attachments/assets/74ca4391-2ec2-408a-9061-fcdbc1036381)

![image](https://github.com/user-attachments/assets/f270e704-db7b-4eaa-be85-e8f00306e756)

**Comment by Womsxd** [comment]
打码平台建议timeout加到90

**Comment by hggg666** [comment]
那httpx的timeout是不是也要改成90秒？不知道这个httpx是否会和验证码那里有关联

**Comment by Womsxd** [comment]
不会，我之前以为是游戏签到超时，才让你改request.py那边的通用配置

**Comment by hggg666** [comment]
哦哦 了解  谢谢大佬指教
