### ISSUE TITLE
这个报错是依赖问题吗

### ISSUE THREAD

**Issue by grinxxoo** [Womsxd/MihoyoBBSTools#46]
## 开始执行... 2023-05-10 07:40:56

2023-05-10T07:40:57 INFO AutoMihoyoBBS Multi User mode
2023-05-10T07:40:57 INFO 正在搜索配置文件！
2023-05-10T07:40:57 INFO 已搜索到2个配置文件，正在开始执行！
2023-05-10T07:40:57 INFO 正在执行mhy_[1].yaml
2023-05-10T07:40:57 INFO Config加载完毕
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/sync.py", line 62, in start_tls
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/sync.py", line 57, in start_tls
    sock = ssl_context.wrap_socket(
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1106: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection.py", line 86, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection.py", line 63, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_sync/connection.py", line 150, in _connect
    stream = stream.start_tls(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/sync.py", line 62, in start_tls
    raise exc
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout: _ssl.c:1106: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 39, in <module>
    multi()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 24, in multi
    status_code, message = main_multi(True)
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main_multi.py", line 52, in main_multi
    run_code, run_message = main.main()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 31, in main
    login.login()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/login.py", line 21, in login
    data = http.get(url=setting.bbs_cookie_url.format(config.config["account"]["login_ticket"])).json()
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1041, in get
    return self.request(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: _ssl.c:1106: The handshake operation timed out

## 执行结束... 2023-05-10 07:41:18  耗时 22 秒

**Comment by grinxxoo** [comment]
还是我的python有问题？

**Comment by grinxxoo** [comment]
或者ck获取错误？能示例下所需的字段吗
