### ISSUE TITLE
点赞分享任务成功，但是游戏签到报错 httpx.LocalProtocolError: Illegal header value b'

### ISSUE THREAD

**Issue by hanuxxx** [Womsxd/MihoyoBBSTools#58]
首次运行，运行方式为docker-compose

一直到分享都很顺利，到游戏签到就报错停止了

```
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:10 INFO 使用DOCKER运行米游社签到
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:10 INFO Starting signing
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:11 INFO AutoMihoyoBBS Multi User mode
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:11 INFO 正在搜索配置文件！
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:11 INFO 已搜索到1个配置文件，正在开始执行！
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:11 INFO 正在执行config.yaml
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:11 INFO Config加载完毕
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:25 INFO HTTP Request: GET https://webapi.account.mihoyo.com/Api/cookie_accountinfo_by_loginticket?login_ticket=xxxxxxxxxx "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:38 INFO HTTP Request: GET https://api-takumi.mihoyo.com/auth/api/getMultiTokenByLoginTicket?login_ticket=xxxxxxxxx "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:38 INFO 登录成功！
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:38 INFO 正在保存Config！
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:38 INFO Config保存完毕
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:44 INFO 正在获取任务列表
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:46 INFO HTTP Request: GET https://bbs-api.mihoyo.com/apihub/sapi/getUserMissionsState "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:46 INFO 似乎还有任务没完成，今天还能获得60个米游币
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:46 INFO 正在获取帖子列表......
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:46 INFO HTTP Request: GET https://bbs-api.mihoyo.com/post/api/getForumPostList?forum_id=26&is_good=false&is_hot=false&page_size=20&sort_type=1 "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:46 INFO 已获取5个帖子
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:46 INFO 讨论区任务已经完成过了~
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:46 INFO 正在看帖......
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:47 INFO HTTP Request: GET https://bbs-api.mihoyo.com/post/api/getPostFull?post_id=39639081 "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:52 INFO 正在点赞......
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:30:53 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:02 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:08 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:15 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:21 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:27 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:34 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:42 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:49 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:55 INFO HTTP Request: POST https://bbs-api.mihoyo.com/apihub/sapi/upvotePost "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:58 INFO 正在执行分享任务......
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:58 INFO HTTP Request: GET https://bbs-api.mihoyo.com/apihub/api/getShareConf?entity_id=39639081&entity_type=1 "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:31:58 INFO 分享任务执行成功......
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:32:01 INFO 正在获取任务列表
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:32:01 INFO HTTP Request: GET https://bbs-api.mihoyo.com/apihub/sapi/getUserMissionsState "HTTP/1.1 200 OK"
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:32:01 INFO 今天已经获得90个米游币，还能获得0个米游币，目前有45250个米游币
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:32:05 INFO 正在进行原神签到
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:32:05 INFO 正在获取米哈游账号绑定的原神账号列表...
mihoyobbstools-mihoyo-bbs-1  | Traceback (most recent call last):
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
mihoyobbstools-mihoyo-bbs-1  |     yield
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 125, in _send_request_headers
mihoyobbstools-mihoyo-bbs-1  |     event = h11.Request(
mihoyobbstools-mihoyo-bbs-1  |             ^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/h11/_events.py", line 96, in __init__
mihoyobbstools-mihoyo-bbs-1  |     self, "headers", normalize_and_validate(headers, _parsed=_parsed)
mihoyobbstools-mihoyo-bbs-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/h11/_headers.py", line 164, in normalize_and_validate
mihoyobbstools-mihoyo-bbs-1  |     validate(_field_value_re, value, "Illegal header value {!r}", value)
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/h11/_util.py", line 91, in validate
mihoyobbstools-mihoyo-bbs-1  |     raise LocalProtocolError(msg)
mihoyobbstools-mihoyo-bbs-1  | h11._util.LocalProtocolError: Illegal header value b'cookie_token_v2=xxxxxxxxxx; '
mihoyobbstools-mihoyo-bbs-1  |
mihoyobbstools-mihoyo-bbs-1  | During handling of the above exception, another exception occurred:
mihoyobbstools-mihoyo-bbs-1  |
mihoyobbstools-mihoyo-bbs-1  | Traceback (most recent call last):
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
mihoyobbstools-mihoyo-bbs-1  |     yield
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 218, in handle_request
mihoyobbstools-mihoyo-bbs-1  |     resp = self._pool.handle_request(req)
mihoyobbstools-mihoyo-bbs-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
mihoyobbstools-mihoyo-bbs-1  |     raise exc
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
mihoyobbstools-mihoyo-bbs-1  |     response = connection.handle_request(request)
mihoyobbstools-mihoyo-bbs-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 90, in handle_request
mihoyobbstools-mihoyo-bbs-1  |     return self._connection.handle_request(request)
mihoyobbstools-mihoyo-bbs-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 116, in handle_request
mihoyobbstools-mihoyo-bbs-1  |     raise exc
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 84, in handle_request
mihoyobbstools-mihoyo-bbs-1  |     self._send_request_headers(**kwargs)
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 124, in _send_request_headers
mihoyobbstools-mihoyo-bbs-1  |     with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
mihoyobbstools-mihoyo-bbs-1  |     self.gen.throw(typ, value, traceback)
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
mihoyobbstools-mihoyo-bbs-1  |     raise to_exc(exc)
mihoyobbstools-mihoyo-bbs-1  | httpcore.LocalProtocolError: Illegal header value b'cookie_token_v2=xxxxxxxxxxxxxxx; '
mihoyobbstools-mihoyo-bbs-1  |
mihoyobbstools-mihoyo-bbs-1  | The above exception was the direct cause of the following exception:
mihoyobbstools-mihoyo-bbs-1  |
mihoyobbstools-mihoyo-bbs-1  | Traceback (most recent call last):
mihoyobbstools-mihoyo-bbs-1  |   File "/var/app/./main_multi.py", line 86, in <module>
mihoyobbstools-mihoyo-bbs-1  |     main_multi(autorun)
mihoyobbstools-mihoyo-bbs-1  |   File "/var/app/./main_multi.py", line 52, in main_multi
mihoyobbstools-mihoyo-bbs-1  |     run_code, run_message = main.main()
mihoyobbstools-mihoyo-bbs-1  |                             ^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/var/app/main.py", line 96, in main
mihoyobbstools-mihoyo-bbs-1  |     genshin_help = genshin.Genshin()
mihoyobbstools-mihoyo-bbs-1  |                    ^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/var/app/genshin.py", line 7, in __init__
mihoyobbstools-mihoyo-bbs-1  |     super(Genshin, self).__init__("hk4e_cn", setting.genshin_checkin_rewards)
mihoyobbstools-mihoyo-bbs-1  |   File "/var/app/gamecheckin.py", line 18, in __init__
mihoyobbstools-mihoyo-bbs-1  |     self.account_list = get_account_list(self.game_id, self.headers)
mihoyobbstools-mihoyo-bbs-1  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/var/app/account.py", line 11, in get_account_list
mihoyobbstools-mihoyo-bbs-1  |     req = http.get(setting.account_Info_url + game_id, headers=headers)
mihoyobbstools-mihoyo-bbs-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1041, in get
mihoyobbstools-mihoyo-bbs-1  |     return self.request(
mihoyobbstools-mihoyo-bbs-1  |            ^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 814, in request
mihoyobbstools-mihoyo-bbs-1  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
mihoyobbstools-mihoyo-bbs-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
mihoyobbstools-mihoyo-bbs-1  |     response = self._send_handling_auth(
mihoyobbstools-mihoyo-bbs-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
mihoyobbstools-mihoyo-bbs-1  |     response = self._send_handling_redirects(
mihoyobbstools-mihoyo-bbs-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
mihoyobbstools-mihoyo-bbs-1  |     response = self._send_single_request(request)
mihoyobbstools-mihoyo-bbs-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
mihoyobbstools-mihoyo-bbs-1  |     response = transport.handle_request(request)
mihoyobbstools-mihoyo-bbs-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 217, in handle_request
mihoyobbstools-mihoyo-bbs-1  |     with map_httpcore_exceptions():
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
mihoyobbstools-mihoyo-bbs-1  |     self.gen.throw(typ, value, traceback)
mihoyobbstools-mihoyo-bbs-1  |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
mihoyobbstools-mihoyo-bbs-1  |     raise mapped_exc(message) from exc
mihoyobbstools-mihoyo-bbs-1  | httpx.LocalProtocolError: Illegal header value b'cookie_token_v2=xxxxxxxxxxxx; '
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:32:19 INFO Current running datetime: 2023-05-28 23:32:19
mihoyobbstools-mihoyo-bbs-1  | 2023-05-28T23:32:19 INFO Next run datetime: 2023-05-29 09:30:35
```

**Comment by Womsxd** [comment]
感觉是cookie的问题

**Comment by hanuxxx** [comment]
> 感觉是cookie的问题

尝试了多次获取新的cookie仍然报错，我愿意提供cookie供测试，请问有空帮排查一下问题吗
