### ISSUE TITLE
又是获取帖子列表失败

### ISSUE THREAD

**Issue by Zmincrix** [Womsxd/MihoyoBBSTools#90]
米游社
## 开始执行... 2023-11-01 05:25:43

2023-11-01T05:25:44 INFO Config加载完毕
2023-11-01T05:25:44 INFO 正在获取任务列表
2023-11-01T05:25:45 INFO 似乎还有任务没完成，今天还能获得60个米游币
2023-11-01T05:25:45 INFO 正在获取帖子列表......
Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 41, in <module>
    single()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 14, in single
    status_code, message = main()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 88, in main
    return_data += run_bbs()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 32, in run_bbs
    bbs = mihoyobbs.Mihoyobbs()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 49, in __init__
    self.postsList = self.get_list()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 116, in get_list
    data = req.json()["data"]["list"]
TypeError: 'NoneType' object is not subscriptable

## 执行结束... 2023-11-01 05:25:46  耗时 3 秒　　　　　
可见能正常识别到还有任务未完成,服务器没炸

**Comment by Zmincrix** [comment]
现在连用户1也有问题了

**Comment by Womsxd** [comment]
[files.zip](https://github.com/Womsxd/MihoyoBBSTools/files/13222279/files.zip)
替换掉压缩包里面这两个文件，看看日志

**Comment by JHeyzo** [comment]
2023-11-01T22:32:51 INFO Config加载完毕
Traceback (most recent call last):
  File "ql_main.py", line 41, in <module>
    single()
  File "ql_main.py", line 14, in single
    status_code, message = main()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 71, in main
    login.login()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/login.py", line 32, in login
    config.config["account"]["stoken"] = data["data"]["list"][0]["token"]
TypeError: 'NoneType' object is not subscriptable

重装替换完了还是一样

**Comment by qwinwin** [comment]
> [files.zip](https://github.com/Womsxd/MihoyoBBSTools/files/13222279/files.zip) 替换掉压缩包里面这两个文件，看看日志

2023-11-01T22:34:26 DEBUG Converted retries value: 10 -> Retry(total=10, connect=None, read=None, redirect=None, status=None)
2023-11-01T22:34:26 DEBUG Converted retries value: 10 -> Retry(total=10, connect=None, read=None, redirect=None, status=None)
2023-11-01T22:34:26 INFO Config加载完毕
2023-11-01T22:34:26 INFO 正在获取任务列表
2023-11-01T22:34:26 DEBUG Starting new HTTPS connection (1): bbs-api.miyoushe.com:443
2023-11-01T22:34:27 DEBUG https://bbs-api.miyoushe.com:443 "GET /apihub/sapi/getUserMissionsState HTTP/1.1" 200 466
2023-11-01T22:34:27 INFO 似乎还有任务没完成，今天还能获得90个米游币
2023-11-01T22:34:27 INFO 正在获取帖子列表......
2023-11-01T22:34:27 DEBUG https://bbs-api.miyoushe.com:443 "GET /post/api/getForumPostList?forum_id=26&is_good=False&is_hot=False&page_size=20&sort_type=1 HTTP/1.1" 200 82
2023-11-01T22:34:27 DEBUG {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
Traceback (most recent call last):
  File "/ql/data/repo/Womsxd_MihoyoBBSTools/main.py", line 129, in <module>
    status_code, message = main()
  File "/ql/data/repo/Womsxd_MihoyoBBSTools/main.py", line 88, in main
    return_data += run_bbs()
  File "/ql/data/repo/Womsxd_MihoyoBBSTools/main.py", line 32, in run_bbs
    bbs = mihoyobbs.Mihoyobbs()
  File "/ql/data/repo/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 49, in __init__
    self.postsList = self.get_list()
  File "/ql/data/repo/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 117, in get_list
    data = req.json()["data"]["list"]
TypeError: 'NoneType' object is not subscriptable

**Comment by Womsxd** [comment]
```json
{"data":null,"message":"Something went wrong...please retry later","retcode":-502}
```
502这问题是偶发性还是

**Comment by qwinwin** [comment]
> ```json
> {"data":null,"message":"Something went wrong...please retry later","retcode":-502}
> ```
> 
> 502这问题是偶发性还是

每次都

![image](https://github.com/Womsxd/MihoyoBBSTools/assets/32760119/a7eaea1a-d6eb-4bc1-80b1-ee3799cc1752)

**Comment by Womsxd** [comment]
> &is_good=False&is_hot=False&page_size=20&sort_type=1

很遗憾，我这边没法复现出这个问题，有尝试重新抓取cookie或者换个地方试试？

**Comment by qwinwin** [comment]
> 很遗憾，我这边没法复现出这个问题，有尝试重新抓取cookie或者换个地方试试？

替换新ck无效，用docker重新部署了一个可以了  好奇怪  莫非是识别了硬件id之类的？

**Comment by Womsxd** [comment]
> > 很遗憾，我这边没法复现出这个问题，有尝试重新抓取cookie或者换个地方试试？
> 
> 替换新ck无效，用docker重新部署了一个可以了 好奇怪 莫非是识别了硬件id之类的？

这倒不可能

**Comment by lllder** [comment]
同样遇到这个问题 ，原因是请求"GET /post/api/getForumPostList?forum_id=26&is_good=False&is_hot=False&page_size=20&sort_type=1 HTTP/1.1" 中False 大写 ，将其替换为"false"解决
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/79615789/4f4ffc41-d5c4-4c8f-8fe6-58bbe0d898af)

**Comment by Womsxd** [comment]
> 同样遇到这个问题 ，原因是请求"GET /post/api/getForumPostList?forum_id=26&is_good=False&is_hot=False&page_size=20&sort_type=1 HTTP/1.1" 中False 大写 ，将其替换为"false"解决 ![image](https://user-images.githubusercontent.com/79615789/283743153-4f4ffc41-d5c4-4c8f-8fe6-58bbe0d898af.png)

感觉这个问题很奇怪，部分用户没遇到，部分用户是这种情况
