### ISSUE TITLE
触发验证码时因打码平台返回时间过长报错

### ISSUE THREAD

**Issue by DaBaiMao233** [Womsxd/MihoyoBBSTools#94]
日志
```
## 开始执行... 2023-11-15 10:55:00

2023-11-15T10:55:03 INFO Config加载完毕
2023-11-15T10:55:03 INFO 正在获取任务列表
2023-11-15T10:55:03 INFO 新的一天，今天可以获得100个米游币
2023-11-15T10:55:03 INFO 正在获取帖子列表......
2023-11-15T10:55:04 INFO 已获取5个帖子
2023-11-15T10:55:04 INFO 正在签到......
2023-11-15T10:55:04 WARNING 社区签到触发验证码
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 41, in <module>
    single()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/ql_main.py", line 14, in single
    status_code, message = main()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/main.py", line 70, in main
    bbs.signing()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 137, in signing
    challenge = self.get_pass_challenge()
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/mihoyobbs.py", line 59, in get_pass_challenge
    validate = captcha.bbs_captcha(data["data"]["gt"], data["data"]["challenge"])
  File "/ql/data/scripts/Womsxd_MihoyoBBSTools/captcha.py", line 18, in bbs_captcha
    rep = http.post(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1132, in post
    return self.request(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out


## 执行结束... 2023-11-15 10:55:25  耗时 25 秒　　　　　
```
打码结果（第二项为耗时）
![image](https://github.com/Womsxd/MihoyoBBSTools/assets/64312558/00b2aa7b-0248-4969-914c-231d34369433)

建议调长等待时间

**Comment by Womsxd** [comment]
http.post(timeout=120)，可以加一个timeout，而且本项目也没对接打码平台(
只是预留了个打码接口(
